### ISSUE TITLE
Portfolio Page

### ISSUE THREAD

**Issue by JaredMabus** [JaredMabus/jaredmabusth-portfolio#1]
## To-do:
- [x] Name, avatar, and links to sections
- [x] Header links scroll to the corresponding sections 
- [x] First application's image is larger than the others
- [x] Application links send to the deployed application
- [x] Responsive page layout
